### ISSUE TITLE
Fatal error after fresh install

### ISSUE THREAD

**Issue by jlnbdt** [YunoHost-Apps/halcyon_ynh#6]
Hi,

I've just installed this app. I get the following message when I try to access it:

>  Fatal error: Uncaught Error: Class 'Locale' not found in /var/www/halcyon/language.php:6 Stack trace: #0 /var/www/halcyon/header.php(4): include() #1 /var/www/halcyon/home.php(1): include('/var/www/halcyo...') #2 /var/www/halcyon/index.php(1): include('/var/www/halcyo...') #3 {main} thrown in /var/www/halcyon/language.php on line 6

Since it seems related to language, I've tried to modify the default language in config.ini (I've tried fr_FR and en_US) ; it doesn't change anything.

Thanks!

**Comment by anmol26s** [comment]
but is the app working?

**Comment by jlnbdt** [comment]
Not at all, I only get this message.

**Comment by anmol26s** [comment]
I have updated the app. Can you try to reinstall?

**Comment by jlnbdt** [comment]
The message is gone but I get a blank page now.
From Nginx log, I get this:

![capture](https://imgur.com/qiWlIan.png)

**Comment by anmol26s** [comment]
> Enable all locales on your system which are supported by Halcyon by uncommenting them in /etc/locale.gen and run locale-gen after that.

I see this warning in the installation page of the Halcyon. I think you can try to uncomment your language and then try to install again.

**Comment by jlnbdt** [comment]
fr_FR is already uncommented, as en_US (and I ran locale-gen). I've tried to reinstalled the app twice (with fr_FR then en_US), it doesn't change anything :-(

**Comment by anmol26s** [comment]
@jlnbdt 
Can you please install php7.0-intl and php-gettext by following command. 

`$ apt-get install php7.0-intl php-gettext`

**Comment by jlnbdt** [comment]
Thank you! Installing php7.0-intl did the job (php-gettext was already installed)

**Comment by anmol26s** [comment]
This package needs to be added in the dependencies so that issue can be fixed. So reopening this.

**Comment by anmol26s** [comment]
Fixed in this https://github.com/YunoHost-Apps/halcyon_ynh/commit/9ae2797a7a3d3a94abc4d8033285cb2cc9fe3398 commit. Closing it.
